/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RfpServicesRouteImport } from './routes/rfp-services'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CapabilityRouteImport } from './routes/capability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasestudiesDistrictwideDataKansasRouteImport } from './routes/casestudies/districtwide-data-kansas'
import { Route as ApiDownloadFilenameRouteImport } from './routes/api/download.$filename'

const RfpServicesRoute = RfpServicesRouteImport.update({
  id: '/rfp-services',
  path: '/rfp-services',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityRoute = CapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasestudiesDistrictwideDataKansasRoute =
  CasestudiesDistrictwideDataKansasRouteImport.update({
    id: '/casestudies/districtwide-data-kansas',
    path: '/casestudies/districtwide-data-kansas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDownloadFilenameRoute = ApiDownloadFilenameRouteImport.update({
  id: '/api/download/$filename',
  path: '/api/download/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRoute
  '/rfp-services': typeof RfpServicesRoute
  '/casestudies/districtwide-data-kansas': typeof CasestudiesDistrictwideDataKansasRoute
  '/api/download/$filename': typeof ApiDownloadFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRoute
  '/rfp-services': typeof RfpServicesRoute
  '/casestudies/districtwide-data-kansas': typeof CasestudiesDistrictwideDataKansasRoute
  '/api/download/$filename': typeof ApiDownloadFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRoute
  '/rfp-services': typeof RfpServicesRoute
  '/casestudies/districtwide-data-kansas': typeof CasestudiesDistrictwideDataKansasRoute
  '/api/download/$filename': typeof ApiDownloadFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capability'
    | '/case-studies'
    | '/rfp-services'
    | '/casestudies/districtwide-data-kansas'
    | '/api/download/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capability'
    | '/case-studies'
    | '/rfp-services'
    | '/casestudies/districtwide-data-kansas'
    | '/api/download/$filename'
  id:
    | '__root__'
    | '/'
    | '/capability'
    | '/case-studies'
    | '/rfp-services'
    | '/casestudies/districtwide-data-kansas'
    | '/api/download/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilityRoute: typeof CapabilityRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  RfpServicesRoute: typeof RfpServicesRoute
  CasestudiesDistrictwideDataKansasRoute: typeof CasestudiesDistrictwideDataKansasRoute
  ApiDownloadFilenameRoute: typeof ApiDownloadFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rfp-services': {
      id: '/rfp-services'
      path: '/rfp-services'
      fullPath: '/rfp-services'
      preLoaderRoute: typeof RfpServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability': {
      id: '/capability'
      path: '/capability'
      fullPath: '/capability'
      preLoaderRoute: typeof CapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casestudies/districtwide-data-kansas': {
      id: '/casestudies/districtwide-data-kansas'
      path: '/casestudies/districtwide-data-kansas'
      fullPath: '/casestudies/districtwide-data-kansas'
      preLoaderRoute: typeof CasestudiesDistrictwideDataKansasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$filename': {
      id: '/api/download/$filename'
      path: '/api/download/$filename'
      fullPath: '/api/download/$filename'
      preLoaderRoute: typeof ApiDownloadFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilityRoute: CapabilityRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  RfpServicesRoute: RfpServicesRoute,
  CasestudiesDistrictwideDataKansasRoute:
    CasestudiesDistrictwideDataKansasRoute,
  ApiDownloadFilenameRoute: ApiDownloadFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
