/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RfpServicesRouteImport } from './routes/rfp-services'
import { Route as DistrictwideDataRouteImport } from './routes/districtwide-data'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CapabilityRouteImport } from './routes/capability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesTicketingRouteImport } from './routes/case-studies.ticketing'

const RfpServicesRoute = RfpServicesRouteImport.update({
  id: '/rfp-services',
  path: '/rfp-services',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictwideDataRoute = DistrictwideDataRouteImport.update({
  id: '/districtwide-data',
  path: '/districtwide-data',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityRoute = CapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesTicketingRoute = CaseStudiesTicketingRouteImport.update({
  id: '/ticketing',
  path: '/ticketing',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/districtwide-data': typeof DistrictwideDataRoute
  '/rfp-services': typeof RfpServicesRoute
  '/case-studies/ticketing': typeof CaseStudiesTicketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/districtwide-data': typeof DistrictwideDataRoute
  '/rfp-services': typeof RfpServicesRoute
  '/case-studies/ticketing': typeof CaseStudiesTicketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capability': typeof CapabilityRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/districtwide-data': typeof DistrictwideDataRoute
  '/rfp-services': typeof RfpServicesRoute
  '/case-studies/ticketing': typeof CaseStudiesTicketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capability'
    | '/case-studies'
    | '/districtwide-data'
    | '/rfp-services'
    | '/case-studies/ticketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capability'
    | '/case-studies'
    | '/districtwide-data'
    | '/rfp-services'
    | '/case-studies/ticketing'
  id:
    | '__root__'
    | '/'
    | '/capability'
    | '/case-studies'
    | '/districtwide-data'
    | '/rfp-services'
    | '/case-studies/ticketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilityRoute: typeof CapabilityRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  DistrictwideDataRoute: typeof DistrictwideDataRoute
  RfpServicesRoute: typeof RfpServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rfp-services': {
      id: '/rfp-services'
      path: '/rfp-services'
      fullPath: '/rfp-services'
      preLoaderRoute: typeof RfpServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districtwide-data': {
      id: '/districtwide-data'
      path: '/districtwide-data'
      fullPath: '/districtwide-data'
      preLoaderRoute: typeof DistrictwideDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability': {
      id: '/capability'
      path: '/capability'
      fullPath: '/capability'
      preLoaderRoute: typeof CapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/ticketing': {
      id: '/case-studies/ticketing'
      path: '/ticketing'
      fullPath: '/case-studies/ticketing'
      preLoaderRoute: typeof CaseStudiesTicketingRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesTicketingRoute: typeof CaseStudiesTicketingRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesTicketingRoute: CaseStudiesTicketingRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilityRoute: CapabilityRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  DistrictwideDataRoute: DistrictwideDataRoute,
  RfpServicesRoute: RfpServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
